#!/usr/bin/fish

argparse d/dir= g/go -- $argv
or return

set -f args

if set -q _flag_go
  set args $args -g
end

if set -q _flag_dir
  set args $args $_flag_d
else
  set args $args build
end


fd -E build '.*\.(cpp|h)$' | entr -dps './cppbldit '"$args"' $argv[1]'
